#!/usr/bin/env python3
"""
Query Neo4j AuraDB for all QUOTE nodes and save results to markdown
"""

import os
import sys
from neo4j import GraphDatabase
from datetime import datetime
from pathlib import Path

# Try to load from .env file if python-dotenv is available
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

# Neo4j AuraDB Connection - from environment variables
URI = os.environ.get("NEO4J_URI", "")
USERNAME = os.environ.get("NEO4J_USERNAME", "")
PASSWORD = os.environ.get("NEO4J_PASSWORD", "")

OUTPUT_FILE = Path("/Users/quasaur/Developer/Neo4j-Thoughts/ANALYSIS/auradb_quotes.md")


def validate_config():
    """Validate that required environment variables are set"""
    missing = []
    if not URI:
        missing.append("NEO4J_URI")
    if not USERNAME:
        missing.append("NEO4J_USERNAME")
    if not PASSWORD:
        missing.append("NEO4J_PASSWORD")
    
    if missing:
        print("❌ ERROR: Missing required environment variables:")
        for var in missing:
            print(f"   - {var}")
        print("\nSet these variables in your environment or create a .env file")
        sys.exit(1)


def query_quotes():
    """Query all QUOTE nodes from AuraDB"""
    validate_config()
    
    driver = GraphDatabase.driver(URI, auth=(USERNAME, PASSWORD))
    
    try:
        print("Connecting to AuraDB...")
        
        with driver.session() as session:
            # Query all QUOTE nodes with their properties
            result = session.run("""
                MATCH (q:QUOTE)
                RETURN q.name as name, 
                       q.parent as parent, 
                       q.source as source
                ORDER BY q.name
            """)
            
            quotes = []
            for record in result:
                quotes.append({
                    "name": record["name"],
                    "parent": record["parent"],
                    "source": record["source"]
                })
            
            print(f"Found {len(quotes)} QUOTE nodes")
            return quotes
            
    finally:
        driver.close()


def generate_markdown(quotes):
    """Generate markdown report from quotes data"""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    md_content = f"""# AuraDB QUOTE Nodes Report

**Generated:** {timestamp}  
**Source:** Neo4j AuraDB  
**Total QUOTE Nodes:** {len(quotes)}

---

## Summary

| Property | Description |
|----------|-------------|
| **name** | Unique identifier for the QUOTE node |
| **parent** | Associated TOPIC node |
| **source** | Book or publication source |

---

## QUOTE Nodes

| # | Name | Parent | Source |
|---|------|--------|--------|
"""
    
    for i, quote in enumerate(quotes, 1):
        name = quote["name"] or "N/A"
        parent = quote["parent"] or "N/A"
        source = quote["source"] or "N/A"
        
        # Escape pipe characters in source
        source = source.replace("|", "\\|")
        
        md_content += f"| {i} | `{name}` | `{parent}` | {source} |\n"
    
    # Add footer
    md_content += f"""
---

## Statistics

- **Total QUOTE nodes:** {len(quotes)}
- **Unique parents:** {len(set(q["parent"] for q in quotes if q["parent"]))}
- **With source:** {len([q for q in quotes if q["source"]])}
- **Without source:** {len([q for q in quotes if not q["source"]])}

---

*Report generated by ANALYSIS/query_quotes_auradb.py*
"""
    
    return md_content


def main():
    print("=" * 80)
    print("QUERYING AURADB FOR QUOTE NODES")
    print("=" * 80)
    print()
    
    # Query the database
    quotes = query_quotes()
    
    # Generate markdown
    markdown = generate_markdown(quotes)
    
    # Save to file
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write(markdown)
    
    print(f"\n✅ Report saved to: {OUTPUT_FILE}")
    print(f"   Total QUOTE nodes: {len(quotes)}")


if __name__ == "__main__":
    main()
